### ISSUE TITLE
Console Error - Did not observe any item or terminal signal within 3000ms in 'publishOn'

### ISSUE THREAD

**Issue by lpjn** [DenisD3D/Mc2Discord#100]
### Describe the bug

`[12:19:53] [parallel-49/ERROR] [fr.de.mc.sh.re.co.pu.Operators/]: Operator called default onErrorDropped
fr.denisd3d.mc2discord.shadow.reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 3000ms in 'publishOn' (and no fallback has been configured)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 3000ms in 'publishOn' (and no fallback has been configured)
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at fr.denisd3d.mc2discord.shadow.reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[mc2discord-forge-1.20.1-4.2.3%20(1).jar%23366!/:4.2.3] {re:classloading}
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] {}
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}`
        
 This seems to trigger in the console every now and then, even when the server is idle
 
 On version 1.20.1-4.2.3

**Comment by DenisD3D** [comment]
You can safely ignore thoses error. The Discord bot retry when needed. They are mostly due to a network connection being a bit unstable and shouldn't prevent the mod from working
