### ISSUE TITLE
MC2Discord Not working mc -> discord

### ISSUE THREAD

**Issue by blacksythe** [DenisD3D/Mc2Discord#70]
### Describe the bug

Discord -> mc is ok

With the latest forge fuckery in version 40.1.84
mc 1.18.2
version 3.2.11

mc2discord has been incapable of sending messages from mc 2 discord (pun intended)

Console produces the following error message

at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at TRANSFORMER/mc2discord@3.2.11/ml.denisd3d.mc2discord.repack.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)

### Your config file

[mc2discord.toml.txt](https://github.com/DenisD3D/Mc2Discord/files/9871295/mc2discord.toml.txt)

**Comment by blacksythe** [comment]
Additional debug information
https://hastebin.com/ilobilucof.properties

**Comment by DenisD3D** [comment]
The error message from you first message isn't complete. Please send the complete block.
Often when the link doesn't work mc -> discord, it's due to missing webhook permission. Please check the /mc2discord info command or send the link returned by the /mc2discord upload command

**Comment by blacksythe** [comment]
Debug logs will try and fix this as it may be an issue with recent discord cahnges

**Comment by blacksythe** [comment]
Thanks, ended up being a permissions issue. I was so confused because everything but 1.18 packs were working so i naturally blamed forge instead of myself.
