### ISSUE TITLE
Issue sending or receiving messages in 1.12.2

### ISSUE THREAD

**Issue by sprocketaudio** [DenisD3D/Mc2Discord#75]
Hi, I can see the mod connects with my bot, but fails to send or receive any messages with the following log in the consol:

[ INFO] (Mc2Discord) Discord4J 3.2.2 (https://discord4j.com)
[ INFO] (ml.denisd3d.mc2discord.repack.reactor-http-nio-5) [G:3eb583e2, S:0] Connected to Gateway
[ INFO] (ml.denisd3d.mc2discord.repack.reactor-http-nio-5) [G:3eb583e2, S:0] Shard connected
[18:39:41] [d4j-events-1/INFO]: Discord bot connected as SB3Bot
[ERROR] (boundedElastic-1) Operator called default onErrorDropped - ml.denisd3d.mc2discord.repack.reactor.core.Exceptions$ErrorCallbackNotImplemented: ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientException: POST /channels/1054408552363589732/webhooks returned 400 Bad Request with response {code=50035, message=Invalid Form Body, errors={name={_errors=[{code=USERNAME_INVALID_CONTAINS, message=Username cannot contain "discord"}]}}}
[18:39:42] [boundedElastic-1/INFO]: [ml.denisd3d.mc2discord.repack.reactor.core.publisher.Operators:onErrorDropped:636]: ml.denisd3d.mc2discord.repack.reactor.core.Exceptions$ErrorCallbackNotImplemented: ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientException: POST /channels/1054408552363589732/webhooks returned 400 Bad Request with response {code=50035, message=Invalid Form Body, errors={name={_errors=[{code=USERNAME_INVALID_CONTAINS, message=Username cannot contain "discord"}]}}}
[18:39:42] [boundedElastic-1/INFO]: [ml.denisd3d.mc2discord.repack.reactor.util.Loggers$ConsoleLogger:error:618]: Caused by: ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientException: POST /channels/1054408552363589732/webhooks returned 400 Bad Request with response {code=50035, message=Invalid Form Body, errors={name={_errors=[{code=USERNAME_INVALID_CONTAINS, message=Username cannot contain "discord"}]}}}
[18:39:42] [boundedElastic-1/INFO]: [ml.denisd3d.mc2discord.repack.reactor.util.Loggers$ConsoleLogger:error:618]:       at ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientResponse.clientException(ClientResponse.java:171)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:  Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ Request to POST /channels/1054408552363589732/webhooks [RequestStream]
        *__checkpoint ⇢ Request to POST /channels/1054408552363589732/webhooks [DefaultRouter]
Original Stack Trace:
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientResponse.clientException(ClientResponse.java:171)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.discord4j.rest.http.client.ClientResponse.lambda$createException$13(ClientResponse.java:149)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at ml.denisd3d.mc2discord.repack.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18:39:42] [boundedElastic-1/INFO]: [java.lang.Throwable:printStackTrace:644]:          at java.lang.Thread.run(Thread.java:748)

**Comment by DenisD3D** [comment]
Please upgrade to mc2discord 3.3.0. This issue was introduced by a "surprise" breaking change from Discord, preventing usage of new channels. It is solve in recent versions.
